### PR TITLE
Update mobile_apps.md

### PR DESCRIPTION
**Pull request by JohnOwais**

### CODE REVIEW

**Comment by JohnOwais** [comment]
Data source: WORLDOMETER and COVID19INDIA.

**Comment by sudevschiz** [comment]
The description and screenshots in the play store app seem to be referring to something else. Why is that so @JohnOwais

**Comment by JohnOwais** [comment]
It is the screenshot and description of the game, that can be played when the app is opened in offline mode. It helps people in staying busy with the app, rather staying idle which reduces chances of depression. @sudevschiz

**Comment by JohnOwais** [comment]
Add my app

**Comment by bee-rickey** [comment]
Screenshot 2020-06-13 at 1 07 50 AM
The playstore screenshots are of a game?

**Comment by JohnOwais** [comment]
Google Play Store removed all screenshots and suggested to use earlier screenshots and description due to new policies. I have raised a ticket regarding this issue, it will be resolved soon.

**Comment by JohnOwais** [comment]
I think you won't add my app. It's okay brother. Completely fine. Anyways, you are doing a great job and I really like your website, especially maps. All the best brother.

**Pull request closed without merging**
