### PR TITLE
Request to add https://www.rt-india.live/

### PR DESCRIPTION
**Pull request by rohitxsh93**

### CODE REVIEW

**Comment by rohitxsh93** [comment]
Thanks for approving the commit but the change is not visible, I think there is some issue!

**Comment by sudevschiz** [comment]
Oh, let me manually add this.

**Comment by rohitxsh93** [comment]
Thanks :)

**Comment by rohitxsh93** [comment]
Just a reminder!

**Comment by JunaidBabu** [comment]
image
https://github.com/covid19india/api#contributing

**Pull request merged**
