### PR TITLE
Districe wise report of recovered and deceased cases

### PR DESCRIPTION
**Pull request by Arusara**

### CODE REVIEW

**Comment by sudevschiz** [comment]
How have you made changes to `state_district_wise_new.json` ? Is it manual?

Changing the json once doesn't help. You will have to make changes in https://github.com/covid19india/api/blob/master/sheet-to-json.js so that these delta values are computed every time the action is run.

**Comment by Arusara** [comment]
sure @sudevschiz let's start to make change.

**Comment by Arusara** [comment]
its giving following error in my system when running **node sheet-to-json.js**
Fetching data from sheets: undefined...
(node:43352) UnhandledPromiseRejectionWarning: Error: Need a Google Drive sheet id to load

**Comment by Arusara** [comment]
@sudevschiz could you please help me this error to resolve 
Fetching data from sheets: 1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk...
(node:44613) UnhandledPromiseRejectionWarning: Error: Error 302 retrieving https://spreadsheets.google.com/feeds/list/1nzXUdaIWC84QipdVGUKTiCSc5xntBbpMpzLm6Si33zk/owlnkho/public/values?alt=json

**Comment by Arusara** [comment]
i don't have sheet id details.

**Comment by Arusara** [comment]
Closing this PR since its become conflict.

**Pull request closed without merging**
