### PR TITLE
Allow district delta time till 7 AM IST to be in sync with state delta

### PR DESCRIPTION
**Pull request by nishcthulhu**
See Issue 1104 on react : https://github.com/covid19india/covid19india-react/issues/1104

District delta needs to keep ebing updated till 730AM IST

### CODE REVIEW

**Comment by nishcthulhu** [comment]
@sudevschiz can you help get this PR merged

**Comment by JunaidBabu** [comment]
This is shifting the day by 7 hours 30 mins right? This will contain wrong values.
What we need is a conditional check

if(time before 7:30am in India){
delta contain everything added yesterday and today.
}else{
delta contain everything added today
}

**Comment by nishcthulhu** [comment]
isToday value is only being used just like you have described.

There is no other use of "isToday" in the file.

See line 37

**Comment by nishcthulhu** [comment]
@JunaidBabu

**Comment by nishcthulhu** [comment]
https://github.com/covid19india/api/issues/124

**Comment by JunaidBabu** [comment]
The current logic in this PR is to add every case reported within the previous day 7:30AM to current day 7:30AM to the delta right?

What we need is, add every case that's reported from 00:00 to 23:59 in the previous day if the current time is before 7:30AM and if it is after 7:30AM, show all the cases added since current day beginning (00:00).

Simple example, if there is a new cases added at 1:00AM, it should not be shown in the delta till 7:30AM for the current day. It should only show up after 7:30AM

**Comment by nishcthulhu** [comment]
@JunaidBabu I believe  that is what the code is doing.

System Time between 12 midnight to 730 am is adjusted to the previous due to the change in UTC offset value. Only the values row values in the raw_data.json that correspond to the previous day will add to the delta based on the IsToday value being true only for those rows till 730 AM

Isn't that the expected behaviour?

**Comment by JunaidBabu** [comment]
Sorry I got confused with time.. 🙇 
Thank you 
Merging this.

**Pull request merged**
