### PR TITLE
Adding covid19bihar.info link

### PR DESCRIPTION
**Pull request by drupler**

### CODE REVIEW

**Comment by sudevschiz** [comment]
Getting a privacy error while trying to access the site. Could you fix that?

**Comment by drupler** [comment]
@sudevschiz - I am not getting that. SSL is powered by letsencrypt and it's working fine as far as I see.

**Comment by drupler** [comment]
> ### `[](url)`

**Comment by sudevschiz** [comment]
Noticed that the links on your page redirects to Ad loops. Very sleazy and unprofessional of you to do that. If you want to add ads, add ads in plain sight - do not trick users.

Rejecting the PR.

cc @JunaidBabu

**Comment by drupler** [comment]
@sudevschiz All I can see is, your browser seems to be crazy. First privacy error and then ad loop. If I would put ad, obviously I would put in plain sight...what purpose would a loop serve..xD. Blamming of cheating user..wow. 

Anyway, I have closed PR, no need of your mighty favour or those millions of users which can come our way to be cheated..Thanks!

**Pull request closed without merging**
