### PR TITLE
COVID 19 tracker for Karnataka

### PR DESCRIPTION
**Pull request by AbhishekPednekar84**
Updated miscellaneous.md to include kar.covid19-info.website/

### CODE REVIEW

**Comment by sudevschiz** [comment]
Hi, getting a privacy/malware alert when trying to reach your website. Could you please fix that?

**Comment by AbhishekPednekar84** [comment]
Thanks! I'll check and get back

**Comment by AbhishekPednekar84** [comment]
Hello, could you please verify this again when you get a chance? Thanks!

While I could not replicate the privacy/malware alert, I did get the sub-domain verified in the Google Search Console. Since then, I have run the site through various blacklist checkers and none of them have reported it as malicious or infected with malware.

**Comment by bee-rickey** [comment]
@AbhishekPednekar84 can you please resolve the conflicts? Will merge after that.

**Comment by AbhishekPednekar84** [comment]
Resolved. Thanks!

**Pull request merged**
