### PR TITLE
Documentation for JSON APIs

### PR DESCRIPTION
**Pull request by cibinjoseph**
Add documentation for the JSON APIs as individual markdown files in a `docs/` directory.  
Each documentation page contains:
1. A _header_ containing the title, the link and the source
2. The JSON _hierarchy_ depicted as a tree
3. A _table_ with the JSON fields, their data types and details of each

The `docs/` directory also contains `toolsNtemplates/` to generate the tree structure using a python code.  

Ps. This PR is discussed in issue #25

### CODE REVIEW

**Comment by JunaidBabu** [comment]
1. How are the files in `/toolsNtemplates` created?
2. If there is a change in the sheet column, will we have to generate these again?

**Comment by cibinjoseph** [comment]
For minor changes, the markdown files can be edited directly.

For now, the tree structure is created by using a template .py file and passing it to generateDocs.py. The table and headers were manually created.

I can take a look at automating it fully. But I might need more time to work out that logic.

**Comment by cibinjoseph** [comment]
To clarify, for a minor change, edit the md file directly.

For major changes in json hierarchy or for a new api, the workflow is:
1. Create .py template file that has the hierarchy information
2. Pass it to generate Docs to get the tree structure in a .md file.
3. Add table and header to the .md file.

**Comment by cibinjoseph** [comment]
I just went over some code and on second thought, I think I can fully automate generation of documentation from the json api link. This workflow is just too cumbersome.

I'll close this PR for now and open a new one in a while.

**Pull request closed without merging**
