### PR TITLE
District wise activities

### PR DESCRIPTION
**Pull request by sumitmckv**
Added district wise activities.
Needed for: https://github.com/covid19india/covid19india-react/issues/292
Sample response:
https://github.com/sumitmckv/api/blob/9101831728977887fac25898b3aa3b015981d242/activities.json

### CODE REVIEW

**Comment by bwayne2015** [comment]
This looks good..
@JunaidBabu your thoughts

**Comment by krishnasen2401** [comment]
people are asking for json format change as its not parse able by non programming platforms
https://github.com/covid19india/api/issues/42#issue-590464837

**Comment by JunaidBabu** [comment]
> Sample response:
> https://github.com/sumitmckv/api/blob/9101831728977887fac25898b3aa3b015981d242/activities.json

This only shows the changes in the current day?

I've already added another API which can be used to show the recent data updates. the below link will give last 50 changes.
https://api.covid19india.org/updatelog/log.json

**Comment by sumitmckv** [comment]
Closing this PR as we already have https://api.covid19india.org/updatelog/log.json

**Pull request closed without merging**
