### PR TITLE
Documentation for JSON API links

### PR DESCRIPTION
**Pull request by cibinjoseph**
Add documentation for the JSON APIs as individual markdown files in a docs/ directory.  
Links to documentation are also added to the table in README.

Each documentation page contains:
1. A header containing the title, the link and the source
2. The JSON hierarchy depicted as a tree
3. A table with the JSON fields, their data types and details of each

Two Python3 helper scripts are also added in `docs/toolsNtemplates/` to generate these markdown files _automagically_ from the API links.
1. `generateDocs.py`
2. `json2tree.py`

**Workflow for generating new documentation later down the road**:
1. Add the new json api link to `generateDocs.py` in the dict variable `api`
2. Run `generateDocs.py` to generate all md files.
3. In the generated md file, fill the title in the header.

Ps. This PR is discussed in issue #25

### CODE REVIEW

**Comment by sudevschiz** [comment]
@cibinjoseph , making few more changes to the type of endpoints we will provide. Few things are in pipeline. Keep this PR open, will update it in a few days and then merge. Thank you

**Comment by cibinjoseph** [comment]
@sudevschiz You guys done with the changes to the endpoints?

**Comment by sudevschiz** [comment]
@cibinjoseph Not really. Added couple more yesterday. 
Also, planning on a massive restructuring for a v2 version. Might need some help from you on that.

**Comment by cibinjoseph** [comment]
Sure!

**Comment by sudevschiz** [comment]
@cibinjoseph Thanks for your hardwork. @bee-rickey is now writing documentation for the available end-points now. Not using this technique though.

**Comment by cibinjoseph** [comment]
No worries. I'll close this PR then.

**Pull request closed without merging**
