### PR TITLE
Adding Projects using this API

### PR DESCRIPTION
**Pull request by drankitbangar**
Hello, I am not sure how to do this because I'm new on github, but please add the dashboard as project using this API. You may change the name if need be.

### CODE REVIEW

**Comment by JunaidBabu** [comment]
Is this created by using the data from this repository?
https://bit.ly/India-COVID19-realtime

**Comment by drankitbangar** [comment]
Yes.

**Comment by drankitbangar** [comment]
> Is this created by using the data from this repository?
> 
> https://bit.ly/India-COVID19-realtime

Is there a reason I’m seeing that the request got declined?

**Comment by JunaidBabu** [comment]
Sorry for the late reply.. could you please resolve the conflicts? @drankitbangar

**Pull request merged**
